### PR TITLE
data update

### PR DESCRIPTION
**Pull request by e8725144**

### CODE REVIEW

**Comment by e8725144** [comment]
Delivery NB included

**Comment by Eszti** [comment]
> Missing values are indicated by a colon. Numbers may be accompanied by a 1- or 2-letter code with the following meaning:
> 
> b: break in time series
> bp: break in time series, provisional
> p: provisional
> e: estimated
> ep: estimated, provisional
> For the purpose of this study, this information is ignored and hence the characters removed, facilitating conversion of the data to numeric.

These lines have been pasted twice. Was it intentionally?

**Comment by Eszti** [comment]
In the `dataLang` DataFrame we have `nPopulation | nEmigrants | nImmigrants | nInternetUsers` columns. From which year does this data come from? Or is it an aggregate?

**Comment by ghost** [comment]
Regarding the immigration/emigration/population data line plots: I think it might be nice to use a big enough colour palette s.t. every country can have its own colour. E.g. for the immigration plot, it's hard to know whether the "highest" dark blue line is Sweden, Spain, or in an unlikely case even Luxembourg.

**Pull request merged**
